### ISSUE TITLE
[Saltmine Standards] Service: Enable: 

### ISSUE THREAD

**Issue by esacteksab** [saltops/saltmine#9]
in: https://github.com/saltops/saltmine/blob/master/saltmine/services/nginx.sls

You have

```
nginx-service:
  service:
    - dead
    - name: nginx
    - enable: False
    - require:
      - pkg: nginx-pkg
      - user: nginx
      - group: nginx
```

emphasis on:

```
- enable: False
```

While in: https://github.com/saltops/saltmine/blob/master/saltmine/services/haproxy.sls

You have

```
haproxy-service:
  service:
    - dead
    - name: haproxy
    - enable:
      - false
    - require:
      - pkg: haproxy-pkg
      # - user: haproxy
      # - group: haproxy
```

Emphasis on:

```
- enable:
    - false
```

https://github.com/saltops/saltmine/blob/master/saltmine_standards.md here you use the haproxy example

Perhaps nginx.sls should be update? or? 

Consistency is key! So which is it? What's the standard? 

Looking at the docs http://docs.saltstack.org/en/latest/ref/states/all/salt.states.service.html  I'm curious if the haproxy way even works?
